# 1 .what was the rate of increase or decrease in crime from 2020 to 2023 which ethnicity or group of people were targeted the most

In [16]:
import pandas as pd
import numpy as np

In [17]:
pd.read_csv('Crime_Data_from_2020_to_Present.csv')
df = pd.read_csv('Crime_Data_from_2020_to_Present.csv')

 DATA UNDERSTANDING

In [18]:
df.head(10)

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,Mocodes,Vict Age,Vict Sex,Vict Descent,Premis Cd,Premis Desc,Weapon Used Cd,Weapon Desc,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,190326475,03/01/2020 12:00:00 AM,03/01/2020 12:00:00 AM,2130,7,Wilshire,784,1,510,VEHICLE - STOLEN,NaN,0,M,O,101.0,STREET,NaN,NaN,AA,Adult Arrest,510.0,998.0,NaN,NaN,1900 S LONGWOOD AV,NaN,34.0375,-118.3506
1,200106753,02/09/2020 12:00:00 AM,02/08/2020 12:00:00 AM,1800,1,Central,182,1,330,BURGLARY FROM VEHICLE,1822 1402 0344,47,M,O,128.0,BUS STOP/LAYOVER (ALSO QUERY 124),NaN,NaN,IC,Invest Cont,330.0,998.0,NaN,NaN,1000 S FLOWER ST,NaN,34.0444,-118.2628
2,200320258,11/11/2020 12:00:00 AM,11/04/2020 12:00:00 AM,1700,3,Southwest,356,1,480,BIKE - STOLEN,0344 1251,19,X,X,502.0,"MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)",NaN,NaN,IC,Invest Cont,480.0,NaN,NaN,NaN,1400 W 37TH ST,NaN,34.0210,-118.3002
3,200907217,05/10/2023 12:00:00 AM,03/10/2020 12:00:00 AM,2037,9,Van Nuys,964,1,343,SHOPLIFTING-GRAND THEFT ($950.01 & OVER),0325 1501,19,M,O,405.0,CLOTHING STORE,NaN,NaN,IC,Invest Cont,343.0,NaN,NaN,NaN,14000 RIVERSIDE DR,NaN,34.1576,-118.4387
4,220614831,08/18/2022 12:00:00 AM,08/17/2020 12:00:00 AM,1200,6,Hollywood,666,2,354,THEFT OF IDENTITY,1822 1501 0930 2004,28,M,H,102.0,SIDEWALK,NaN,NaN,IC,Invest Cont,354.0,NaN,NaN,NaN,1900 TRANSIENT,NaN,34.0944,-118.3277
5,231808869,04/04/2023 12:00:00 AM,12/01/2020 12:00:00 AM,2300,18,Southeast,1826,2,354,THEFT OF IDENTITY,1822 0100 0930 0929,41,M,H,501.0,SINGLE FAMILY DWELLING,NaN,NaN,IC,Invest Cont,354.0,NaN,NaN,NaN,9900 COMPTON AV,NaN,33.9467,-118.2463
6,230110144,04/04/2023 12:00:00 AM,07/03/2020 12:00:00 AM,900,1,Central,182,2,354,THEFT OF IDENTITY,0930 0929,25,M,H,502.0,"MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)",NaN,NaN,IC,Invest Cont,354.0,NaN,NaN,NaN,1100 S GRAND AV,NaN,34.0415,-118.2620
7,220314085,07/22/2022 12:00:00 AM,05/12/2020 12:00:00 AM,1110,3,Southwest,303,2,354,THEFT OF IDENTITY,0100,27,F,B,248.0,CELL PHONE STORE,NaN,NaN,IC,Invest Cont,354.0,NaN,NaN,NaN,2500 S SYCAMORE AV,NaN,34.0335,-118.3537
8,231309864,04/28/2023 12:00:00 AM,12/09/2020 12:00:00 AM,1400,13,Newton,1375,2,354,THEFT OF IDENTITY,0100,24,F,B,750.0,CYBERSPACE,NaN,NaN,IC,Invest Cont,354.0,NaN,NaN,NaN,1300 E 57TH ST,NaN,33.9911,-118.2521
9,211904005,12/31/2020 12:00:00 AM,12/31/2020 12:00:00 AM,1220,19,Mission,1974,2,624,BATTERY - SIMPLE ASSAULT,0416,26,M,H,502.0,"MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)",400.0,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",IC,Invest Cont,624.0,NaN,NaN,NaN,9000 CEDROS AV,NaN,34.2336,-118.4535

In [19]:
df.tail(10)

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,Mocodes,Vict Age,Vict Sex,Vict Descent,Premis Cd,Premis Desc,Weapon Used Cd,Weapon Desc,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
955329,240405919,02/27/2024 12:00:00 AM,02/26/2024 12:00:00 AM,1545,4,Hollenbeck,422,1,761,BRANDISH WEAPON,0216 0334 0371 0906,18,M,H,102.0,SIDEWALK,101.0,REVOLVER,IC,Invest Cont,761.0,NaN,NaN,NaN,THOMAS ST,BALDWIN ST,34.0703,-118.2052
955330,242107144,02/22/2024 12:00:00 AM,02/19/2024 12:00:00 AM,1125,21,Topanga,2187,1,442,SHOPLIFTING - PETTY THEFT ($950 & UNDER),1420 0325 0216,50,M,W,406.0,OTHER STORE,NaN,NaN,IC,Invest Cont,442.0,NaN,NaN,NaN,21900 VENTURA BL,NaN,34.1685,-118.6038
955331,240905054,01/31/2024 12:00:00 AM,01/30/2024 12:00:00 AM,2230,9,Van Nuys,901,1,330,BURGLARY FROM VEHICLE,0344 1300 1307,36,M,W,108.0,PARKING LOT,NaN,NaN,IC,Invest Cont,330.0,NaN,NaN,NaN,15300 SHERMAN WY,NaN,34.2012,-118.4725
955332,241605414,02/16/2024 12:00:00 AM,01/19/2024 12:00:00 AM,1415,16,Foothill,1619,2,354,THEFT OF IDENTITY,1822 1202 0930,62,F,W,501.0,SINGLE FAMILY DWELLING,NaN,NaN,IC,Invest Cont,354.0,NaN,NaN,NaN,11100 PROVENCE LN,NaN,34.2707,-118.2917
955333,241605270,02/11/2024 12:00:00 AM,02/11/2024 12:00:00 AM,1920,16,Foothill,1681,2,888,TRESPASSING,0913 1202 1501,79,M,O,501.0,SINGLE FAMILY DWELLING,NaN,NaN,AA,Adult Arrest,888.0,NaN,NaN,NaN,8700 SHARP AV,NaN,34.2278,-118.4051
955334,241604405,01/14/2024 12:00:00 AM,01/13/2024 12:00:00 AM,720,16,Foothill,1673,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",0400 1822 1310 0416,36,M,H,101.0,STREET,207.0,OTHER KNIFE,IC,Invest Cont,230.0,NaN,NaN,NaN,8700 LANKERSHIM BL,NaN,34.2271,-118.3878
955335,242106032,02/20/2024 12:00:00 AM,02/17/2024 12:00:00 AM,2330,21,Topanga,2103,1,420,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),0385,44,F,O,104.0,DRIVEWAY,NaN,NaN,IC,Invest Cont,420.0,NaN,NaN,NaN,22700 NAPA ST,NaN,34.2260,-118.6214
955336,242004546,01/16/2024 12:00:00 AM,01/16/2024 12:00:00 AM,1510,20,Olympic,2013,2,624,BATTERY - SIMPLE ASSAULT,2047 0400 0429 0444 1202 1822,80,F,O,124.0,BUS STOP,400.0,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",IC,Invest Cont,624.0,NaN,NaN,NaN,HOBART BL,3RD ST,34.0690,-118.3054
955337,240104953,01/15/2024 12:00:00 AM,01/15/2024 12:00:00 AM,100,1,Central,101,2,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),0329 0400 0416,0,X,X,503.0,HOTEL,500.0,UNKNOWN WEAPON/OTHER WEAPON,IC,Invest Cont,745.0,NaN,NaN,NaN,1300 W SUNSET BL,NaN,34.0685,-118.2460
955338,240309674,04/24/2024 12:00:00 AM,04/24/2024 12:00:00 AM,1500,3,Southwest,358,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",1822 0334 0416 0445 0449 1202,70,F,W,102.0,SIDEWALK,308.0,STICK,IC,Invest Cont,230.0,NaN,NaN,NaN,FLOWER ST,JEFFERSON BL,34.0215,-118.2868

In [20]:
df.sample(15)

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,Mocodes,Vict Age,Vict Sex,Vict Descent,Premis Cd,Premis Desc,Weapon Used Cd,Weapon Desc,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
608880,230604934,01/13/2023 12:00:00 AM,12/14/2022 12:00:00 AM,230,6,Hollywood,646,1,440,THEFT PLAIN - PETTY ($950 & UNDER),1822 0394,40,M,K,502.0,"MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)",NaN,NaN,AA,Adult Arrest,440.0,NaN,NaN,NaN,1300 N LAS PALMAS AV,NaN,34.0944,-118.3363
829260,231419019,10/12/2023 12:00:00 AM,10/11/2023 12:00:00 AM,916,14,Pacific,1469,1,442,SHOPLIFTING - PETTY THEFT ($950 & UNDER),0344 0325,40,M,H,404.0,DEPARTMENT STORE,NaN,NaN,IC,Invest Cont,442.0,NaN,NaN,NaN,6900 LA TIJERA BL,NaN,33.9761,-118.3732
236501,210507454,03/30/2021 12:00:00 AM,03/30/2021 12:00:00 AM,2235,5,Harbor,567,2,624,BATTERY - SIMPLE ASSAULT,0416 0913,21,M,H,501.0,SINGLE FAMILY DWELLING,400.0,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",AO,Adult Other,624.0,NaN,NaN,NaN,400 W 21ST ST,NaN,33.7251,-118.2858
28982,200619330,12/16/2020 12:00:00 AM,12/16/2020 12:00:00 AM,1125,6,Hollywood,639,1,442,SHOPLIFTING - PETTY THEFT ($950 & UNDER),1822 0325 0344,0,X,X,203.0,OTHER BUSINESS,NaN,NaN,IC,Invest Cont,442.0,NaN,NaN,NaN,5400 HOLLYWOOD BL,NaN,34.1036,-118.3049
538732,220110796,04/20/2022 12:00:00 AM,04/19/2022 12:00:00 AM,2300,1,Central,111,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",0329 1414 1413 1822,41,M,H,748.0,CULTURAL SIGNIFICANCE/MONUMENT,NaN,NaN,IC,Invest Cont,740.0,NaN,NaN,NaN,100 PASEO DE LA PLAZA,NaN,34.0615,-118.2412
576215,221604243,01/08/2022 12:00:00 AM,01/08/2022 12:00:00 AM,1215,16,Foothill,1656,1,310,BURGLARY,0344 1402,43,M,O,101.0,STREET,NaN,NaN,IC,Invest Cont,310.0,998.0,NaN,NaN,8700 WYNGATE ST,NaN,34.2585,-118.3222
227168,210114812,08/07/2021 12:00:00 AM,08/07/2021 12:00:00 AM,1310,1,Central,166,2,624,BATTERY - SIMPLE ASSAULT,0416 2004 0910 1822,69,F,H,801.0,MTA BUS,400.0,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",IC,Invest Cont,624.0,NaN,NaN,NaN,7TH ST,WALL,34.0420,-118.2485
167000,201515700,09/29/2020 12:00:00 AM,09/29/2020 12:00:00 AM,130,15,N Hollywood,1557,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",1822 1309 0400 1310 0450 1300,44,M,B,101.0,STREET,102.0,HAND GUN,IC,Invest Cont,230.0,NaN,NaN,NaN,VINELAND,HESBY,34.1620,-118.3703
697832,230114014,06/11/2023 12:00:00 AM,06/11/2023 12:00:00 AM,650,1,Central,151,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",2004 1218 0411 1822,30,M,W,102.0,SIDEWALK,223.0,UNKNOWN TYPE CUTTING INSTRUMENT,IC,Invest Cont,230.0,NaN,NaN,NaN,6TH,FREMONT,34.0515,-118.2592
800731,230313695,07/15/2023 12:00:00 AM,07/15/2023 12:00:00 AM,234,3,Southwest,399,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",0329 0913,22,X,X,502.0,"MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)",NaN,NaN,IC,Invest Cont,740.0,NaN,NaN,NaN,4000 S FIGUEROA ST,NaN,34.0111,-118.2827
56589,201513159,07/27/2020 12:00:00 AM,07/26/2020 12:00:00 AM,2300,15,N Hollywood,1517,1,510,VEHICLE - STOLEN,NaN,0,NaN,NaN,101.0,STREET,NaN,NaN,IC,Invest Cont,510.0,NaN,NaN,NaN,6600 TUJUNGA AV,NaN,34.1903,-118.3791
882104,240606138,02/14/2024 12:00:00 AM,02/13/2024 12:00:00 AM,1600,6,Hollywood,636,1,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",1822 0344,0,X,X,101.0,STREET,NaN,NaN,IC,Invest Cont,341.0,NaN,NaN,NaN,6500 FRANKLIN AV,NaN,34.1052,-118.3310
298312,211512443,07/24/2021 12:00:00 AM,07/20/2021 12:00:00 AM,1140,15,N Hollywood,1522,2,354,THEFT OF IDENTITY,0377,32,F,W,602.0,BANK,NaN,NaN,IC,Invest Cont,354.0,NaN,NaN,NaN,6600 COLDWATER CANYON AV,NaN,34.1936,-118.4166
149478,202108944,05/04/2020 12:00:00 AM,05/01/2020 12:00:00 AM,1900,21,Topanga,2177,1,420,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),NaN,0,NaN,NaN,101.0,STREET,NaN,NaN,IC,Invest Cont,420.0,NaN,NaN,NaN,5700 OWENSMOUTH AV,NaN,34.1744,-118.6016
8669,200708905,05/04/2020 12:00:00 AM,04/01/2020 12:00:00 AM,900,7,Wilshire,706,2,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),0329 1609,0,M,O,203.0,OTHER BUSINESS,NaN,NaN,IC,Invest Cont,745.0,NaN,NaN,NaN,800 N LA BREA AV,NaN,34.0853,-118.3441

In [22]:
df.shape

(955339, 28)

In [23]:
df.columns

Index(['DR_NO', 'Date Rptd', 'DATE OCC', 'TIME OCC', 'AREA', 'AREA NAME',
       'Rpt Dist No', 'Part 1-2', 'Crm Cd', 'Crm Cd Desc', 'Mocodes',
       'Vict Age', 'Vict Sex', 'Vict Descent', 'Premis Cd', 'Premis Desc',
       'Weapon Used Cd', 'Weapon Desc', 'Status', 'Status Desc', 'Crm Cd 1',
       'Crm Cd 2', 'Crm Cd 3', 'Crm Cd 4', 'LOCATION', 'Cross Street', 'LAT',
       'LON'],
      dtype='object')

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 955339 entries, 0 to 955338
Data columns (total 28 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   DR_NO           955339 non-null  int64
 1   Date Rptd       955339 non-null  object
 2   DATE OCC        955339 non-null  object
 3   TIME OCC        955339 non-null  int64
 4   AREA            955339 non-null  int64
 5   AREA NAME       955339 non-null  object
 6   Rpt Dist No     955339 non-null  int64
 7   Part 1-2        955339 non-null  int64
 8   Crm Cd          955339 non-null  int64
 9   Crm Cd Desc     955339 non-null  object
 10  Mocodes         818664 non-null  object
 11  Vict Age        955339 non-null  int64
 12  Vict Sex        825294 non-null  object
 13  Vict Descent    825284 non-null  object
 14  Premis Cd       955327 non-null  float64
 15  Premis Desc     954770 non-null  object
 16  Weapon Used Cd  325019 non-null  float64
 17  Weapon Desc     325019 non-null  object
 18  Status          955338 non-null  object
 19  Status Desc     955339 non-null  object
 20  Crm Cd 1        955328 non-null  float64
 21  Crm Cd 2        68466 non-null   float64
 22  Crm Cd 3        2294 non-null    float64
 23  Crm Cd 4        64 non-null      float64
 24  LOCATION        955339 non-null  object
 25  Cross Street    148900 non-null  object
 26  LAT             955339 non-null  float64
 27  LON             955339 non-null  float64
dtypes: float64(8), int64(7), object(13)
memory usage: 204.1+ MB

DATA CLEANING

In [37]:
# CONVERSIONS 

df['DATE OCC'  ]= pd.to_datetime(df['DATE OCC'], errors='coerce')
df['Date Rptd']= pd.to_datetime(df['Date Rptd'], errors='coerce')

df[['DATE OCC', 'Date Rptd']].dtypes

DATE OCC     datetime64[ns]
Date Rptd    datetime64[ns]
dtype: object

In [38]:
df['Hour']=df['TIME OCC']//100
df[['TIME OCC','Hour']].head()

   TIME OCC  Hour
0      2130    21
1      1800    18
2      1700    17
3      2037    20
4      1200    12

In [40]:
df.describe()

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,Rpt Dist No,Part 1-2,Crm Cd,Vict Age,Premis Cd,Weapon Used Cd,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LAT,LON,Hour
count,9.553390e+05,955339,955339,955339.000000,955339.000000,955339.000000,955339.000000,955339.000000,955339.000000,955327.000000,325019.000000,955328.000000,68466.000000,2294.000000,64.00000,955339.000000,955339.000000,955339.000000
mean,2.191355e+08,2022-04-11 17:54:26.347547648,2022-03-31 03:54:28.073426688,1338.453032,10.718033,1118.243545,1.407805,500.667710,29.383110,306.255200,363.741547,500.415756,958.107265,984.102005,991.21875,33.993372,-118.074280,13.206543
min,8.170000e+02,2020-01-01 00:00:00,2020-01-01 00:00:00,1.000000,1.000000,101.000000,1.000000,110.000000,-4.000000,101.000000,101.000000,110.000000,210.000000,310.000000,821.00000,0.000000,-118.667600,0.000000
25%,2.105125e+08,2021-03-28 00:00:00,2021-03-14 00:00:00,900.000000,6.000000,621.000000,1.000000,331.000000,0.000000,101.000000,311.000000,331.000000,998.000000,998.000000,998.00000,34.014500,-118.430700,9.000000
50%,2.207106e+08,2022-05-02 00:00:00,2022-04-18 00:00:00,1420.000000,11.000000,1142.000000,1.000000,442.000000,30.000000,203.000000,400.000000,442.000000,998.000000,998.000000,998.00000,34.059000,-118.322500,14.000000
75%,2.307171e+08,2023-05-05 00:00:00,2023-04-23 00:00:00,1900.000000,16.000000,1618.000000,2.000000,626.000000,45.000000,501.000000,400.000000,626.000000,998.000000,998.000000,998.00000,34.164900,-118.274000,19.000000
max,2.499187e+08,2024-06-24 00:00:00,2024-06-24 00:00:00,2359.000000,21.000000,2199.000000,2.000000,956.000000,120.000000,976.000000,516.000000,956.000000,999.000000,999.000000,999.00000,34.334300,0.000000,23.000000
std,1.261589e+07,NaN,NaN,652.186527,6.100431,610.098189,0.491427,206.867837,21.909695,217.844195,123.606085,206.661318,110.316767,51.662269,27.06985,1.660523,5.755746,6.521301

In [39]:
# missing values per column with percentages
missing_values = df.isnull().sum()
missing_percentages = (missing_values / len(df)) * 100
missing_df = pd.DataFrame({'Missing Values': missing_values, 'Percentage': missing_percentages})
print(missing_df)

                Missing Values  Percentage
DR_NO                        0    0.000000
Date Rptd                    0    0.000000
DATE OCC                     0    0.000000
TIME OCC                     0    0.000000
AREA                         0    0.000000
AREA NAME                    0    0.000000
Rpt Dist No                  0    0.000000
Part 1-2                     0    0.000000
Crm Cd                       0    0.000000
Crm Cd Desc                  0    0.000000
Mocodes                 136675   14.306440
Vict Age                     0    0.000000
Vict Sex                130045   13.612445
Vict Descent            130055   13.613492
Premis Cd                   12    0.001256
Premis Desc                569    0.059560
Weapon Used Cd          630320   65.978674
Weapon Desc             630320   65.978674
Status                       1    0.000105
Status Desc                  0    0.000000
Crm Cd 1                    11    0.001151
Crm Cd 2                886873   92.833329
Crm Cd 3                953045   99.759876
Crm Cd 4                955275   99.993301
LOCATION                     0    0.000000
Cross Street            806439   84.413910
LAT                          0    0.000000
LON                          0    0.000000
Hour                         0    0.000000

In [ ]:
#filling all missing values with unknown # will decode later at ML 
 df_filled = df.fillna('Unknown')
df_filled.isnull().sum()

DR_NO             0
Date Rptd         0
DATE OCC          0
TIME OCC          0
AREA              0
AREA NAME         0
Rpt Dist No       0
Part 1-2          0
Crm Cd            0
Crm Cd Desc       0
Mocodes           0
Vict Age          0
Vict Sex          0
Vict Descent      0
Premis Cd         0
Premis Desc       0
Weapon Used Cd    0
Weapon Desc       0
Status            0
Status Desc       0
Crm Cd 1          0
Crm Cd 2          0
Crm Cd 3          0
Crm Cd 4          0
LOCATION          0
Cross Street      0
LAT               0
LON               0
Hour              0
dtype: int64

In [45]:
# checking for duplicates
duplicates = df.duplicated().sum()
print(f'Number of duplicate rows: {duplicates}')

Number of duplicate rows: 0

In [50]:
# checking for unique values 
df.nunique()

DR_NO             955339
Date Rptd           1637
DATE OCC            1637
TIME OCC            1439
AREA                  21
AREA NAME             21
Rpt Dist No         1209
Part 1-2               2
Crm Cd               139
Crm Cd Desc          139
Mocodes           307531
Vict Age             104
Vict Sex               5
Vict Descent          20
Premis Cd            314
Premis Desc          306
Weapon Used Cd        79
Weapon Desc           79
Status                 6
Status Desc            6
Crm Cd 1             141
Crm Cd 2             126
Crm Cd 3              37
Crm Cd 4               6
LOCATION           65865
Cross Street       10206
LAT                 5422
LON                 4979
Hour                  24
dtype: int64

In [68]:
# getting negative values in Vict Age 
negative_ages = df[df['Vict Age'] < 0]
print(negative_ages)

# filling negative ages with zero
df['Vict Age'] = df['Vict Age'].apply(lambda x: 0 if x < 0 else x)

# confirming that there are no more negative ages
print(df[df['Vict Age'] < 0])

Empty DataFrame
Columns: [DR_NO, Date Rptd, DATE OCC, TIME OCC, AREA, AREA NAME, Rpt Dist No, Part 1-2, Crm Cd, Crm Cd Desc, Mocodes, Vict Age, Vict Sex, Vict Descent, Premis Cd, Premis Desc, Weapon Used Cd, Weapon Desc, Status, Status Desc, Crm Cd 1, Crm Cd 2, Crm Cd 3, Crm Cd 4, LOCATION, Cross Street, LAT, LON, Hour]
Index: []
Empty DataFrame
Columns: [DR_NO, Date Rptd, DATE OCC, TIME OCC, AREA, AREA NAME, Rpt Dist No, Part 1-2, Crm Cd, Crm Cd Desc, Mocodes, Vict Age, Vict Sex, Vict Descent, Premis Cd, Premis Desc, Weapon Used Cd, Weapon Desc, Status, Status Desc, Crm Cd 1, Crm Cd 2, Crm Cd 3, Crm Cd 4, LOCATION, Cross Street, LAT, LON, Hour]
Index: []

In [ ]:
#getting  unique values in Vict Sex
print(df['Vict Sex'].unique())

# if unique values not  same as  ['M', 'F'] fill with unknown
if set(df['Vict Sex'].unique()) != {'M', 'F'}:
    df['Vict Sex'] = df['Vict Sex'].fillna('Unknown') 

  # confirming the fill
    print(df['Vict Sex'].unique())

['M' 'X' 'F' 'Unknown' 'H' '-']
['M' 'X' 'F' 'Unknown' 'H' '-']

In [77]:
# getting unique values for Vict Descent
print(df['Vict Descent'].unique())

['O' 'X' 'H' 'B' 'W' nan 'A' 'C' 'K' 'J' 'F' 'I' 'V' 'S' 'P' 'Z' 'G' 'U'
 'D' 'L' '-']

 
missing values converted to unknown  nothing dropped  decode at ML 
vict descent , vict sex  partially noisy but  informative later since too sensitive  to drop 
next EDA